---
title: "Your blog post is You are awesome"
date: 2021-06-19
---

theme: minima
title: Your awesome 
author: Manvi
email: your-email@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You are awesome
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
